# Generated by Django 3.2.4 on 2021-06-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='logo',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(default='No', max_length=4),
        ),
    ]
